quarkus.devservices.enabled=false
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = postgres
quarkus.datasource.password = test_password
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/tangent
dev.quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/tangent

# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.database.generation = none
dev.quarkus.hibernate-orm.database.generation = update
dev.tangent.key=SUPER_SECURE_SECRET_KEY
